import { Metadata } from "next";

export const metadata: Metadata = {
  applicationName: "U+ Studio",
  title: {
    default: "U+ Studio | Mimarlık & Tasarım & Mühendislik",
    template: "%s | U+ Studio",
  },
  description:
    "U+ Studio'da mimari tasarım, iç mekân tasarımı, yeniden işlevlendirme, anahtar teslim projeler, uygulama projeleri, proje yönetimi & teknik koordinasyon ve 3D görselleştirme hizmetleri sunuyoruz. Ankara Gölbaşı'daki ofisimizden konut, ticari ve kamusal projeler için çağdaş çözümler, işlevsel ve estetik mekânlar, kullanıcı odaklı tasarımlar ve gerçekçi sunum görselleri üretiyoruz. Her detay bilinçli. Her mekân güçlü.",
  metadataBase: new URL("https://uplusstudio.com.tr"),
  category: "architecture",
  referrer: "origin-when-cross-origin",

  icons: {
    icon: [
      { url: "/favicon.ico" },
      { url: "/favicon-32x32.png", sizes: "32x32", type: "image/png" },
      { url: "/favicon-16x16.png", sizes: "16x16", type: "image/png" },
    ],
    apple: "/apple-touch-icon.png",
  },

  keywords: [
    "ankara mimarlık ofisi",
    "ankara iç mimarlık",
    "mimari tasarım",
    "proje yönetimi",
    "konut mimarisi",
    "ticari mimarlık",
    "uygulama projeleri",
    "uplus studio",
    "u+ studio mimarlık",
    "iç mekân tasarımı",
    "konsept geliştirme",
    "3D görselleştirme",
    "tasarım danışmanlığı",
    "kamusal alanlar",
    "mimari proje",
    "Hacer Uyar",
    "Rıdvan Uyar",
    "gölbaşı mimarlık",
    "incek mimarlık",
    "ankara mimar",
    "ankara mimar firması",
    "ankara proje müellifi",
    "gölbaşı mimarlık ofisi",
    "incek mimarlık şirketi",
    "ankara iç mimar",
    "ankara dekorasyon",
    "ankara ofis tasarımı",
    "ankara ev tasarımı",
    "ankara villa projesi",
    "ankara apartman projesi",
    "ankara ticari proje",
    "ankara mağaza tasarımı",
    "ankara restoran tasarımı",
    "ankara cafe tasarımı",
    "gölbaşı iç mimarlık",
    "incek iç mimar",
    "ankara 3D mimari görselleştirme",
    "ankara mimari çizim",
    "ankara proje danışmanlığı",
    "ankara inşaat mühendisliği",
    "gölbaşı inşaat mühendisi",
    "incek inşaat projesi",
    "ankara yapı tasarımı",
    "ankara bina projesi",
    "ankara konut tasarımı",
    "ankara mimari çözümler",
    "gölbaşı mimari hizmetler",
    "incek tasarım ofisi",
    "ankara modern mimarlık",
    "ankara minimalist tasarım",
    "ankara lüks mimarlık",
    "ankara sürdürülebilir mimarlık",
    "gölbaşı modern tasarım",
    "incek mimari danışmanlık",
    "ankara ruhsat projeleri",
    "ankara imar uygulama projeleri",
    "gölbaşı ruhsat mimarı",
    "incek yapı ruhsatı",
    "ankara statik proje",
    "ankara elektrik projesi",
    "ankara mekanik projesi",
    "gölbaşı mimari ve mühendislik",
    "incek entegre proje çözümleri",
    "ankara anahtar teslim proje",
    "gölbaşı anahtar teslim inşaat",
    "incek proje yönetimi",
    "ankara şantiye şefliği",
    "ankara mimari kontrol",
    "gölbaşı uygulama kontrolü",
    "incek inşaat denetimi",
    "ankara mimari görselleştirme",
    "ankara 3D render",
    "ankara mimari animasyon",
    "gölbaşı 3D görselleştirme",
    "incek mimari sunum",
    "ankara VR mimari tur",
    "ankara AR mimari uygulama",
    "gölbaşı dijital mimarlık",
    "incek teknolojik tasarım",
    "ankara peyzaj tasarımı",
    "ankara bahçe düzenlemesi",
    "gölbaşı peyzaj mimarlığı",
    "incek dış mekân tasarımı",
    "ankara çevre düzenlemesi",
    "gölbaşı peyzaj projeleri",
    "incek yeşil alan tasarımı",
    "ankara restorasyon",
    "ankara bina restorasyonu",
    "gölbaşı tarihi mimarlık",
    "incek yapı onarımı",
    "ankara mimari koruma",
    "gölbaşı restorasyon projeleri",
    "incek tarihi eser restorasyonu",
    "ankara tadilat",
    "ankara ofis tadilatı",
    "gölbaşı ev tadilatı",
    "incek mağaza tadilatı",
    "ankara bina yenileme",
    "gölbaşı yapı tadilatı",
    "incek iç mekân tadilatı",
    "ankara mimarlık fiyatları",
    "gölbaşı mimarlık ücretleri",
    "incek proje maliyetleri",
    "ankara ekonomik mimarlık",
    "gölbaşı uygun fiyatlı tasarım",
    "incek kaliteli mimarlık",
    "ankara profesyonel mimar",
    "gölbaşı tecrübeli mimar",
    "incek uzman tasarım ekibi",
    "ankara mimarlık firmaları",
    "gölbaşı en iyi mimarlar",
    "incek mimari ofisleri",
    "ankara mimarlık şirketleri",
    "gölbaşı mimar danışmanları",
    "incek tasarım firmaları",
    "yeniden işlevlendirme",
    "bina dönüştürme",
    "yapı yeniden kullanım",
    "mevcut yapı dönüşüm",
    "ofis konut dönüşüm",
    "ticari konut dönüşüm",
    "anahtar teslim projeler",
    "tamamlanmış projeler",
    "proje teslim",
    "mühendislik uygulama",
    "teknik koordinasyon",
    "mimari statik koordinasyon",
    "disiplinler arası koordinasyon",
    "proje yönetimi teknik",
    "uygulanabilir teknik çizimler",
    "uygulama detay projeleri",
    "mimari uygulama çizimleri",
    "teknik çizim hizmetleri",
    "çözümler çağdaş",
    "çağdaş mimari çözümler",
    "modern mimari hizmet",
    "kullanıcı odaklı tasarım",
    "işlevsel estetik mekânlar",
    "kullanıcı merkezli tasarım",
    "estetik işlevsel mimari",
    "gerçekçi sunum görselleri",
    "etkileyici görselleştirme",
    "gerçekçi 3D sunum",
    "etkileyici mimari görseller"
  ],

  authors: [
    { name: "Hacer Uyar", url: "https://uplusstudio.com.tr" },
    { name: "Rıdvan Uyar", url: "https://uplusstudio.com.tr" },
  ],
  creator: "U+ Studio",
  publisher: "U+ Studio",

  formatDetection: {
    email: false,
    address: false,
    telephone: false,
  },

  alternates: {
    canonical: "/",
    languages: {
      "tr-TR": "/tr",
      "en-US": "/en",
    },
  },

  openGraph: {
    type: "website",
    locale: "tr_TR",
    url: "https://uplusstudio.com.tr",
    siteName: "U+ Studio",
    title: "U+ Studio | Mimarlık & Tasarım & Mühendislik",
    description:
"U+ Studio, Ankara Gölbaşı'nda Mimarlık & Tasarım & Mühendislik; mimari tasarım, iç mekân tasarımı, mühendislik, yeniden işlevlendirme, anahtar teslim projeler, uygulama projeleri, proje yönetimi & teknik koordinasyon ve 3D görselleştirme hizmetleri sunmaktadır. Yaratıcı, sürdürülebilir ve mühendislik odaklı çözümlerle her projeye özel tasarımlar üretiyoruz."   , images: [
      {
        url: "images/background.jpeg",
        width: 1200,
        height: 630,
        alt: "U+ Studio Mimarlık & Tasarım",
      },
    ],
  },

  twitter: {
    card: "summary_large_image",
    title: "U+ Studio | Mimarlık & Tasarım & Mühendislik",
    description:
      "U+ Studio'da mimari tasarım, iç mekân tasarımı, yeniden işlevlendirme, anahtar teslim projeler, uygulama projeleri, proje yönetimi & teknik koordinasyon ve 3D görselleştirme hizmetleri. Ankara Gölbaşı'da hizmet veriyoruz.",
    images: ["https://uplusstudio.com.tr/og-image.jpg"],
  },

  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      "max-video-preview": -1,
      "max-image-preview": "large",
      "max-snippet": -1,
    },
  },

  other: {
    "application/ld+json": JSON.stringify({
      "@context": "https://schema.org",
      "@type": "LocalBusiness",
      "name": "U+ Studio",
      "alternateName": "UPlus Studio",
      "description": "Mimarlık, Tasarım ve Mühendislik hizmetleri sunan profesyonel ofis",
      "url": "https://uplusstudio.com.tr",
      "telephone": "+90 545 320 40 07",
      "email": "info@uplusstudio.com.tr",
      "address": {
        "@type": "PostalAddress",
        "streetAddress": "İncek Mahallesi Reyhan caddesi Merkez İncek Plaza No:3 Kat:1 Daire No:2",
        "addressLocality": "Gölbaşı",
        "addressRegion": "Ankara",
        "postalCode": "06830",
        "addressCountry": "TR"
      },
      "geo": {
        "@type": "GeoCoordinates",
        "latitude": "39.808944",
        "longitude": "32.697583"
      },
      "founders": [
        {
          "@type": "Person",
          "name": "Hacer Uyar",
          "jobTitle": "Mimar, Kurucu Ortak"
        },
        {
          "@type": "Person", 
          "name": "Rıdvan Uyar",
          "jobTitle": "İnşaat Mühendisi, Kurucu Ortak"
        }
      ],
      "services": [
        "Mimari Tasarım",
        "İç Mekân Tasarımı", 
        "Yeniden İşlevlendirme",
        "Anahtar Teslim Projeler",
        "Uygulama Projeleri",
        "Proje Yönetimi & Teknik Koordinasyon",
        "3D Görselleştirme",
        "Konut Projeleri",
        "Ticari Projeler",
        "Kamusal Projeler",
        "Çağdaş Mimari Çözümler",
        "İşlevsel Estetik Mekânlar",
        "Kullanıcı Odaklı Tasarım",
        "Teknik Çizim Hizmetleri",
        "Mühendislik Uygulamaları",
        "Gerçekçi Sunum Görselleri"
      ],
      "keywords": [
        "ankara mimarlık ofisi",
        "gölbaşı mimarlık", 
        "incek mimarlık",
        "mimari tasarım",
        "iç mimarlık",
        "proje yönetimi",
        "yeniden işlevlendirme",
        "anahtar teslim projeler",
        "uygulama projeleri",
        "3D görselleştirme",
        "çağdaş mimari çözümler",
        "işlevsel estetik mekânlar",
        "kullanıcı odaklı tasarım",
        "teknik çizim hizmetleri",
        "mühendislik uygulamaları"
      ],
      "sameAs": [
        "https://www.instagram.com/u.plusstudio"
      ],
      "openingHours": "Mo-Fr 09:00-18:00",
      "priceRange": "$$"
    })
  }
};
